#!/bin/bash

epoch=$(date +%s)
tdate=$(date "+%F-%T")
ftdate=${tdate//":"/"-"}

# iterate through each path
cat config.json | jq -c '.paths.upload_pairs[]' |
while read pair; do
    n=$(echo $pair | jq -r '.local_dir')
    filename=$n"_"$epoch"_"$ftdate".tar.gz"
    echo $filename
done	

#path="repo-onedrive-backup/"

#echo "Creating" $filename "..."

#cd /home/snxfz-app/
#tar -zcf $path$filename private_repos/

#cd $path
#python3 upload.py $filename

#echo "Cleaning up..."
#rm $filename
